name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Build demo1 JAR
        working-directory: ./demo1/demo1
        run: mvn clean package -DskipTests

      - name: Build demo2 JAR
        working-directory: ./demo2/demo2
        run: mvn clean package -DskipTests

      - name: Build ApiGateway JAR
        working-directory: ./ApiGateway/ApiGateway
        run: mvn clean package -DskipTests

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Add EC2 Host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 16.171.159.14 >> ~/.ssh/known_hosts

      - name: Copy repo to EC2
        run: |
          rsync -avz --delete --exclude='.git*' ./ ubuntu@16.171.159.14:/home/ubuntu/micros/
        env:
          RSYNC_RSH: ssh

      - name: SSH and Deploy on EC2
        run: |
          ssh ubuntu@16.171.159.14 << 'EOF'
            cd /home/ubuntu/micros
            docker-compose down
            docker-compose up -d --build
          EOF
